# feeder
feeder: feeders.feeder_dhg14_28.Feeder
train_feeder_args:
  data_path: joint  # 模态 joint, bone, motion, bone motion
  label_path: train # 训练
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 150 # max
  normalization: False
  repeat: 5 # 重复
  label_flag: 14 # 14 or 28
  idx: 1
  nw_DHG14_28_root: data/DHG14-28/DHG14-28_shift_bwd/ # change to point to relevant dataset for test

test_feeder_args:
  data_path: joint # 模态
  label_path: val # 验证
  debug: False
  random_choose: False
  idx: 1
  label_flag: 14 # 14 or 28
  nw_DHG14_28_root: data/DHG14-28/DHG14-28_shift_bwd/

# model
model: model.tdgcn.Model
model_args:
  num_class: 14 # 类别数 14 or 28
  num_point: 22 # 关节数
  num_person: 1
  graph: graph.dhg14_28.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001 # 权重衰减
base_lr: 0.1  # 初始学习率
lr_decay_rate: 0.1 # 学习率在epoch[90, 130]衰减0.1
step: [90, 130] # [90, 130]

# training
device: 0
batch_size: 32 # 32
test_batch_size: 32 # 32
num_epoch: 75 # 150
nesterov: True
warm_up_epoch: 20 # 20

work_dir: ./work_dir/dhg14-28/test
phase: test
weights: ./results/dhg_active_071024/runs-53-418488.pt